### ISSUE TITLE
Error isn't shown in console

### ISSUE THREAD

**Issue by lukepighetti** [osaxma/dfs#2]
https://github.com/osaxma/dfs/blob/cf3b9ed358e60eb3986b037cb38ace379f3a9a6e/lib/src/find_unused_top_level/find_unused_top_level.dart#L46-L49

Was just trying this out and the errors appear to be suppressed, which makes it hard to provide feedback/create issues

```
% dfs find-unused-top-level
finding unused top level declarations... |error getting the results
Exception: error getting the results
```

**Comment by osaxma** [comment]
That's weird. It could be related to the dart sdk path..

I added extra logging points as well as printing that error to stderr:

Try updating the package:

```
dart pub global activate --source git https://github.com/osaxma/dfs.git 
```

then run on verbose:
```
dfs find-unused-top-level --verbose
```

My bad ... this was a xmas break project so u know how that goes...

**Comment by osaxma** [comment]
Thanks @lukepighetti for picking that up 🙏🏽 

I believe it's working for u now so I'm closing this.

**Comment by lukepighetti** [comment]
No worries, this is resolved (for me at least!)

**Comment by osaxma** [comment]
Out of curiosity, how many big is your project (LOC or number of packages) and how much time did the command take for you?  (trying to see if 1-minute is good enough or maybe increase it in the future). 

The issue with the analysis server is that when you search the top level declarations, it'll search all packages and there's no way to prevent that. So a large project with many packages would take much longer time.

**Comment by lukepighetti** [comment]
~166k LOC including generated files, 85 deps, 8 dev deps
